name: CI

on:
  push:
    branches: [master]
  pull_request_target:
    branches: ['**']

jobs:
  test:
    name: Run linter and tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v2

    - run: |
        git fetch origin $REF
        git checkout $REF
      env:
        REF: ${{ github.event.pull_request.head.sha || github.sha }}

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Check if dist is updated
      run: |
        npm run build
        set -e # exit immediate if a command below returns a non-zero status
        git status # display the results for debugging
        test -z "$(git status --porcelain)"

    - name: Run linter and tests
      run: |
        npm run lint
        npm test
        npm run coverage

    - name: Send test coverage report to Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
